#!/usr/bin/bash

BASE_DIR="$( readlink -f "$(dirname "$0")" )"
ICON_PATH="$BASE_DIR/openvpn.png"

export SUDO_ASKPASS="$HOME/.scripts/rofi/rofi-askpass"

server="$(systemctl list-units | \
    grep openvpn-client | \
    grep running | \
    awk '{print $1};' | \
    cut -d '@' -f2 | \
    cut -d '.' -f1)"

if [[ "$server" != "" ]]; then
    echo "Stopping openvpn-client@${server}.service..."
    sudo --askpass systemctl stop openvpn-client@${server}.service

if [[ "$res" -eq 0 ]]; then
    summary="OpenVPN ($server)"
    body="OpenVPN client stopped"

    notify-send "$summary" "$body" -u normal -i "$ICON_PATH"
fi
else
    echo "No openvpn service is running"
fi

sudo --askpass sysctl net.ipv6.conf.all.disable_ipv6=0
sudo --askpass sysctl net.ipv6.conf.default.disable_ipv6=0

unset SUDO_ASKPASS
