#!/usr/bin/bash
SERVER_PATH="/etc/openvpn/client"
BASE_DIR="$( readlink -f "$(dirname "$0")" )"
ICON_PATH="$BASE_DIR/openvpn.png"

export SUDO_ASKPASS="$HOME/.scripts/rofi/rofi-askpass"

sudo --askpass sysctl net.ipv6.conf.all.disable_ipv6=1
sudo --askpass sysctl net.ipv6.conf.default.disable_ipv6=1

sudo --askpass ls "$SERVER_PATH" | \
    grep -v 'login.conf' | \
    sed 's/\.conf//' \
    > /tmp/servers

mapfile -t servers < /tmp/servers

chosen="$(printf "%s\n" "${servers[@]}" | rofi -dmenu -p "OpenVPN Server")"

sudo --askpass systemctl start openvpn-client@${chosen}.service
res="$?"

if [[ "$res" -eq 0 ]]; then
    summary="OpenVPN ($chosen)"
    body="OpenVPN client started. Confirm your protection with https://www.expressvpn.com/dns-leak-test"

    notify-send "$summary" "$body" -u normal -i "$ICON_PATH"
fi

rm -f /tmp/servers

unset SUDO_ASKPASS
