#!/usr/bin/sh

rofi_command="rofi -show -theme $HOME/.config/rofi/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=""
reboot="ﰇ"
lock=""
hibernate="鈴"
logout=""

options="$shutdown\n$reboot\n$lock\n$hibernate\n$logout"

chosen=$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)

case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        ~/.scripts/lock
        ;;
    $hibernate)
        amixer set Master mute
        systemctl hibernate
        ;;
    $logout)
        pkill dwm
        ;;
esac
