#!/usr/bin/bash

options=()
summaries=()
lines=()

# Last line does not have newline character
while IFS=$'\n' read -r line || [[ -n "$line" ]]; do
    # Try to parse different properties
    # Format: #<action label> (<summary>) [<notification id>,<action>]
    # The below may not work if there is a '(' in the label
    label="$(echo "$line" | sed -E 's/\(.*\) \[[0-9]+?,.*\]$//' | sed 's/^#//')"
    summary="$(echo "$line" \
        | grep -o -P '\(.*\) \[\d+?,.*\]$' \
        | sed -E 's/ \[[0-9]+?,.*\]$//' \
        | sed 's/^(//' \
        | sed 's/)$//')"
    nid="$(echo "$line" \
        | grep -o -P '\(.*\) \[\d+?,.*\]$' \
        | grep -o -P '\[\d+?,.*\]$' \
        | sed 's/[][]//g' \
        | cut -d',' -f1)"
    action="$(echo "$line" \
        | grep -o -P '\(.*\) \[\d+?,.*\]$' \
        | grep -o -P '\[\d+?,.*\]$' \
        | sed 's/[][]//g' \
        | cut -d',' -f2)"

    # Associate notification summaries with their id
    summaries[nid]="$summary"

    # Get list of newline separated options for notification
    options[nid]="${options[nid]}\n$label"

    # Get list of lines for notification
    lines[nid]="${lines[nid]}\n$line"
done

for i in "${!summaries[@]}"; do
    # Get summary of notification with ID i
    summary="${summaries[i]}"
    # Get labels of notification with ID i
    labels="${options[i]}"

    # Display rofi with $labels as options and get selection
    sel="$(echo -e "$labels" | rofi -i -dmenu -p "$summary")"

    # If an option was selected...
    if [[ "$sel" != "" ]]; then
        # Find the line given by dunst associated with this option
        echo -e "${lines[i]}" | grep "#$sel"

        # Further responses will be ignored by dunst
        exit 0
    fi
done
