#!/usr/bin/bash
SERVER_PATH="/etc/openvpn/client"
BASE_DIR="$( readlink -f "$(dirname "$0")" )"
ICON_PATH="$BASE_DIR/openvpn.png"

mapfile -t servers < <(expressvpn list all \
  | tail -n+3 \
  | sort | sed -E 's/ +/,/' \
  | sed -E 's/  +Y$//g' \
  | sed -E 's/ +$//' \
  | sed -E 's/  +/,/g' \
  | sed -E 's/,.+,/,/')

aliases=("${servers[@]%,*}")
names=("${servers[@]#*,}")

chosen="$(printf "%s\n" "${names[@]}" | rofi -dmenu -i -p "ExpressVPN Server")"

for i in "${!names[@]}"; do
  if [[ "${names[i]}" == "$chosen" ]]; then
    break
  fi
done

selected_alias="${aliases[i]}"

expressvpn connect "$selected_alias"

echo "$selected_alias" > /tmp/expressvpn-alias
