#!/usr/bin/sh

vlc \
    --no-video-deco \
    --no-embedded-video \
    --screen-fps=20 \
    --screen-top=0 \
    --screen-left=1920 \
    --screen-width=1920 \
    --screen-height=1000 \
    --qt-start-minimized \
    screen:// &

disown
