#!/usr/bin/bash

BASE_DIR="$( readlink -f "$(dirname "$0")" )"
ICON_PATH="$BASE_DIR/bluetooth.png"

export SUDO_ASKPASS="$HOME/.scripts/rofi/rofi-askpass"

sudo --askpass systemctl start bluetooth.service
res="$?"

bluetoothctl power on
res=$res && $?

if [[ "$res" -eq 0 ]]; then
    summary="Bluetooth"
    body="Bluetooth powered on"

    notify-send "$summary" "$body" -u normal -i "$ICON_PATH"
fi

unset SUDO_ASKPASS
